<?php

namespace Mba\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository {

    public function getMenuPages() {
        $query = $this->_em->createQuery('
       		SELECT p FROM MbaPageBundle:Page p       			
            	WHERE p.include_in_menu = ?1 
                Order by p.created DESC')
                ->setParameter(1, true);

        $result = $query->getResult();
        return $result ? $result : false;
    }

    public function getPageBySlug($slug) {
        $query = $this->_em->createQuery('
       		SELECT p FROM MbaPageBundle:Page p       			
            	WHERE p.slug = ?1 
                Order by p.id ASC')
                ->setParameter(1, $slug);
        $result = $query->getResult();
        return $result ? $result[0] : false;
    }

}