<?php

namespace Mba\GlobalSettingsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GlobalSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalSettingRepository extends EntityRepository
{
}