<?php

namespace Mba\CautiousBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PodcastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PodcastRepository extends EntityRepository
{
    public function getArchive()
    {
         $conn    = $this->_em->getConnection();            
         $results = $conn->fetchAll('SELECT DATE_FORMAT(p.podcast_date, \'%M %Y\') as adates, DATE_FORMAT(p.podcast_date, \'%M-%Y\') as aldates
            FROM podcast_work p            
            WHERE p.active = ?
            GROup BY DATE_FORMAT(p.podcast_date, \'%M %Y\')
          ', array(true));
                             
        return $results;
    }   
    
    public function getEntriesForDate($date) {
         $conn    = $this->_em->getConnection();            
         $results = $conn->fetchAll('SELECT * 
            FROM podcast_work p            
            WHERE p.active = ?
            AND DATE_FORMAT(p.podcast_date, \'%M-%Y\') = ?
          ', array(true, $date));
                             
        return $results;                
    }
     
}