<?php

namespace Mba\CautiousBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoRepository extends EntityRepository
{
    public function getAll()
    {
        $query = $this->_em->createQuery('
            SELECT p FROM MbaCautiousBundle:Promo p            
            WHERE
                p.active = ?1
            ORDER by p.promo_date DESC');
        $query->setParameter(1, true);        
        $r = $query->getResult();
        return $r ? $r : false;                
    }
    
    public function getLatestPromo()
    {
        $query = $this->_em->createQuery('
            SELECT p FROM MbaCautiousBundle:Promo p            
            WHERE
                p.active = ?1                
            ORDER by p.promo_date DESC ');
        $query->setParameter(1, true);        
        $r = $query->getResult();
        return $r ? $r[0] : false;                
    }    
    
    public function getOneBySlug($slug)
    {
        $query = $this->_em->createQuery('
            SELECT p FROM MbaCautiousBundle:Promo p            
            WHERE
                p.active = ?1
                and p.slug = ?2
            ORDER by p.promo_date DESC');
        $query->setParameter(1, true);        
        $query->setParameter(2, $slug);        
        $r = $query->getResult();
        return $r ? $r[0] : false;                
    }    
}