<?php

namespace Mba\CautiousBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShortFilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortFilmRepository extends EntityRepository {

    public function getAll() {
        $query = $this->_em->createQuery('
            SELECT p FROM MbaCautiousBundle:ShortFilm p            
            WHERE
                p.active = ?1
            ORDER by p.short_film_date DESC');
        $query->setParameter(1, true);

        return $query;
    }

}