<?php

namespace Mba\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository {

    public function getArchive() {
        $conn = $this->_em->getConnection();
        $results = $conn->fetchAll('SELECT DATE_FORMAT(p.entry_date, \'%M %Y\') as adates, DATE_FORMAT(p.entry_date, \'%M-%Y\') as aldates
            FROM blog p            
            WHERE p.active = ?
            GROup BY DATE_FORMAT(p.entry_date, \'%M %Y\')
          ', array(true));

        return $results;
    }

    public function getEntriesForDate($date) {
        $conn = $this->_em->getConnection();
        $results = $conn->fetchAll('SELECT * 
            FROM blog p            
            WHERE p.active = ?
            AND DATE_FORMAT(p.entry_date, \'%M-%Y\') = ?
          ', array(true, $date));

        return $results;
    }

    public function getEntryBySlug($slug) {
         $query = $this->_em->createQuery('
            SELECT p FROM MbaBlogBundle:Blog p            
            WHERE
                p.active = ?1
                and p.slug = ?2
            ORDER by p.id DESC');
        $query->setParameter(1, true);        
        $query->setParameter(2, $slug);        
        $r = $query->getResult();
        return $r ? $r[0] : false;          
    }
    
}